<!-- jQuery Library -->
<script type="text/javascript" src="<?php echo SERVERURL?>/vistas/js/jquery-1.11.2.min.js"></script>    
<!--materialize js-->
<script type="text/javascript" src="<?php echo SERVERURL?>/vistas/js/materialize.js"></script>
<!--scrollbar-->
<script type="text/javascript" src="<?php echo SERVERURL?>/vistas/js/plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>

<!--plugins.js - Some Specific JS codes for Plugin Settings-->
<script type="text/javascript" src="<?php echo SERVERURL?>/vistas/js/plugins.js"></script>
